### ISSUE TITLE
Don't assume Eigen's storage layout

### ISSUE THREAD

**Issue by intractabilis** [CMA-ES/libcmaes#224]
I recently experience issue #135. The reason of not respected boundaries turned out to be here:
```cpp
if (phenocandidates.size())
    _solutions._candidates.at(r).set_fvalue(
        _func(phenocandidates.col(r).data(), candidates.rows()));
```
The expression `phenocandidates.col(r).data()` assumes that the column data is adjacent in memory, which in fact depends on the defaults of the Eigen library. Suggested fix (in eo_matrix.h):
```
typedef Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor> dMat;
typedef Eigen::Matrix<double, Eigen::Dynamic, 1, Eigen::ColMajor> dVec;
```

**Comment by beniz** [comment]
Good catch, can you PR the improvement ? Thanks!
