### ISSUE TITLE
[Doxygen Documentation]

### ISSUE THREAD

**Issue by phbasler** [CMA-ES/libcmaes#237]
Hi @beniz ,

It seems something does not work with the deployment off the doxygen documentation. 

If i check out the gh-pages branch and open the doc/html/index.html with a browser then I get the documentation as expected, but when I open the hosted version on https://beniz.github.io/libcmaes/doc/html/index.html then I only see an empty body of the page. 

Can you check if there is a problem with your gh-pages settings?

**Comment by nikohansen** [comment]
I suspect the link https://cma-es.github.io/libcmaes/doc/html/index.html is the correct one, because the project moved?

**Comment by phbasler** [comment]
Thanks! I will just add the corrected link to the PR
