### ISSUE TITLE
ModuleNotFoundError after cmake

### ISSUE THREAD

**Issue by AtWillTeam** [CMA-ES/libcmaes#241]
Hello,
I have successfully used `cmake .. -DCMAKE_INSTALL_PREFIX=~/.local/ -DLIBCMAES_BUILD_PYTHON=ON` to build the Python bindings. But after `make install` and exporting the LD_LIBRARY_PATH, the ptest.py reports `ModuleNotFoundError: no module named 'lcmaes'`. The processes look successful except some unused parameter warnings in `make install`.
I wonder what causes this issue and how to solve it. Thanks.

**Comment by beniz** [comment]
Try copying the `build/python/lcmaes.so` file into the dir that has `ptest.py` and try again. If it works, then you'll have to figure how to load it from another dir.

**Comment by AtWillTeam** [comment]
I copied it into the `python/` dir where the `ptest.py` is then an `ImportError` occur: `/lib/x86_64-linux-gnu/libboost_python310.so.1.74.0: undefined symbol: PyCMethod_New`.

**Comment by AtWillTeam** [comment]
I wonder if it is possible to control the stop criteria in Python, e.g., stop when the fitness reach a value or the evaluation budget exhausted?
