### ISSUE TITLE
Results of a minimization are out of bound

### ISSUE THREAD

**Issue by marco-palmiotto** [CMA-ES/libcmaes#244]
Hi all, I started using CMA-ES recently, and I wanted to thank you for this remarkable work!

I have a question about bounds to parameters. I am now doing a minimization of a function in 1 variable, imposing a bound on it. I followed the guide, and my code (at least its relevant part) is the following:

    constexpr const int npar=1;
    const double lbounds[1] ={1.0e-20},
                 ubounds[1] ={1.0};
  
    constexpr const double init_seed_g_chi=0.3;
    std::vector<double> x0;
    x0.reserve(npar);
    x0.emplace_back(init_seed_g_chi);

    GenoPheno<pwqBoundStrategy> gp(lbounds,ubounds,npar); // genotype / phenotype transform associated to bounds.
  
    // -1 for automatically decided lambda, 0 is for random	seeding	of the internal generator.           
    CMAParameters<GenoPheno<pwqBoundStrategy>> cmaparams(x0,sigma,-1,0,gp);     
    
    cmaparams.set_algo(aCMAES);
    FitFunc f = function_to_minimize;
    CMASolutions cmasols = cmaes<GenoPheno<pwqBoundStrategy>>(f, cmaparams);
  
    std::cout << "seed g_chi is\n";
    for(int i=0; i < npar ; i++) std::cout <<  x0[i] << '\n';
    std::cout << "\nbest solution: ";
    cmasols.print(std::cout,0,gp);
    std::cout << '\n';
    std::cout << "Expected Distance from Minimum: " << cmasols.edm() << '\n';
    std::cout << "optimization took " << cmasols.elapsed_time() / 1000.0 << " seconds\n";

    Candidate bcand = cmasols.best_candidate();
    double fmin = bcand.get_fvalue(); // min objective function value the optimizer converged to
    std::vector<double> x_stdv = bcand.get_x(); // vector of objective function parameters at minimum.
    const double* x_dptr = bcand.get_x_ptr(); // vector of objective function parameters at minimum, as C-style double array
    Eigen::VectorXd x_ev = bcand.get_x_dvec(); // vector of objective function parameters at minimum, as Eigen vector
    double edm = cmasols.edm(); // expected distance to the minimum.

    std::cout << "# m_chi   m_phi    g_chi   pull-Oh2\nRESULT=";
    std::cout << input.m_chi.get() << '\t' << input.m_phi.get() << '\t' << x_dptr[0] << '\t' << fmin << '\n';
  

where `function_to_minimize` is defined as a lambda function.

The problem is that the result I have is 1.1 for the minimum, which is out of the bound [1.0e-20, 1.0] that I provided. So I wanted to ask you what am I missing.

I have also another question, in case I will open another topic, but it is very simple. Is there a way to "impose" the value of the function at minimum? For instance, I want this function to be 0.0 (because I expect 0 to be its minimum), but instead the f-value is around 30.

Thanks in advance for your answers :) 

EDIT The output is:

    best solution: best solution => f-value=0.345947 / fevals=280 / sigma=0.00112601 / iter=70 / elaps=351247ms / x=1
    Expected Distance from Minimum: 0
    optimization took 351.247 seconds
    # m_chi   m_phi    g_chi   pull-Oh2
    RESULT=10000    22000   1.1     0.345947

I notice now a mismatch between the parameter in the last line and the one in the `best solution` line.

EDIT 2 I tried to "free" another parameter of the function (it actually has 3 parameters, but I wanted to fix 2 and vary just one), and by minimising with 2 parameters I get consistent points (i.e. withn the bounds, and with a value close to 0)

**Comment by marco-palmiotto** [comment]
> Hi, can you show the exact code output ? what value is 1.1, the best solution or the edm ? Also look at this comment and issue [#231 (comment)](https://github.com/CMA-ES/libcmaes/issues/231#issuecomment-1055707309)

Hi, I updated the text of the question, with the output. I looked at the issue you linked, and it appears to me that I should try as well `best_seen_candidate`, and `gp.pheno(best_candidate().get_x_dvec()).transpose()` to display the output. Am I correct?

**Comment by beniz** [comment]
> I notice now a mismatch between the parameter in the last line and the one in the `best solution` line.

You may want to show the code for this last line.

**Comment by marco-palmiotto** [comment]
> > I notice now a mismatch between the parameter in the last line and the one in the `best solution` line.
> 
> You may want to show the code for this last line.

My bad, it was in the updated message, but unformatted. Now it should appear properly.

**Comment by beniz** [comment]
Then I believe you have found the answer in the linked comment above: apply pheno to the best_candidate() output.
